create table sound (
  id bigint generated by default as identity primary key,
  decibel float,
  created_at timestamp with time zone default now()
);

alter table public.sound enable row level security;

create policy "Allow anon read access for dashboard"
  on public.sound
  for select
  to anon
  using (true);

-- Example edge function payload for email alerts
-- Name your function: send-noise-alert
-- Body expected by app.js:
-- {
--   "email": "ops@example.com",
--   "decibel": 96.2,
--   "created_at": "2026-03-11T05:53:44.000Z",
--   "threshold": 90
-- }
