create table sound (
  id bigint generated by default as identity primary key,
  decibel float,
  created_at timestamp with time zone default now()
);

alter table public.sound enable row level security;

create policy "Allow anon read access for dashboard"
  on public.sound
  for select
  to anon
  using (true);

-- App consumes rows from this table for realtime/polling dashboards and local alerts.
